name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GODOT_VERSION: "4.5.0-stable"
  GODOT_DOWNLOAD_URL: "https://github.com/godotengine/godot-builds/releases/download/4.5-dev6/Godot_v4.5-dev6_linux.x86_64.zip"
  GODOT_TEMPLATES_URL: "https://github.com/godotengine/godot-builds/releases/download/4.5-dev6/Godot_v4.5-dev6_export_templates.tpz"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and setup Godot
        run: |
          # Download Godot
          echo "Downloading Godot from ${{ env.GODOT_DOWNLOAD_URL }}"
          wget -v ${{ env.GODOT_DOWNLOAD_URL }} -O godot.zip
          echo "Downloaded Godot, extracting..."
          unzip godot.zip
          ls -la

          # Find the actual executable name
          GODOT_EXEC=$(find . -maxdepth 1 -name "Godot_v4.5*" -type f)
          echo "Found Godot executable: $GODOT_EXEC"
          chmod +x "$GODOT_EXEC"
          sudo mv "$GODOT_EXEC" /usr/local/bin/godot

          # Download export templates
          echo "Downloading export templates from ${{ env.GODOT_TEMPLATES_URL }}"
          wget -v ${{ env.GODOT_TEMPLATES_URL }} -O templates.tpz
          echo "Downloaded templates, extracting..."

          mkdir -p ~/.local/share/godot/export_templates/4.5.dev6
          unzip templates.tpz
          ls -la

          # Find and move templates
          if [ -d "templates" ]; then
            mv templates/* ~/.local/share/godot/export_templates/4.5.dev6/
          else
            echo "Templates directory structure:"
            find . -type d -name "*template*"
            # Try alternative extraction
            unzip -o templates.tpz -d ~/.local/share/godot/export_templates/4.5.dev6/
          fi

          # Verify installation
          godot --version
          echo "Template location:"
          ls -la ~/.local/share/godot/export_templates/

      - name: Export Godot project to HTML5
        run: |
          mkdir -p client_build
          godot --headless --export-release "Web" client_build/index.html

      - name: Verify export
        run: |
          ls -la client_build/
          echo "Export completed successfully"

      - name: Prepare deployment package
        run: |
          mkdir -p deploy_package
          cp -r backend deploy_package/
          cp -r nginx deploy_package/
          cp -r database deploy_package/
          cp -r client_build deploy_package/
          cp docker-compose.yml deploy_package/

      - name: Generate .env file
        run: |
          cat > deploy_package/.env << EOF
          # Database configuration
          DB_USER=${{ vars.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ vars.DB_NAME }}

          # Telegram configuration
          TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}

          # Server configuration
          SERVER_HOST=${{ vars.SERVER_HOST }}
          API_PORT=8000
          EOF

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ vars.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          # Create deployment directory on VPS
          ssh -i ~/.ssh/deploy_key ${{ vars.SSH_USER }}@${{ vars.SERVER_HOST }} \
            "mkdir -p /opt/one-button-game"

          # Copy files to VPS
          scp -i ~/.ssh/deploy_key -r deploy_package/* \
            ${{ vars.SSH_USER }}@${{ vars.SERVER_HOST }}:/opt/one-button-game/

          # Deploy with Docker Compose
          ssh -i ~/.ssh/deploy_key ${{ vars.SSH_USER }}@${{ vars.SERVER_HOST }} << 'ENDSSH'
            cd /opt/one-button-game

            # Pull latest images and rebuild
            docker-compose pull
            docker-compose build --no-cache

            # Stop old containers and start new ones
            docker-compose down
            docker-compose up -d

            # Show status
            docker-compose ps

            # Wait for services to be healthy
            echo "Waiting for services to be healthy..."
            sleep 10
            docker-compose ps
          ENDSSH

      - name: Verify deployment
        run: |
          ssh -i ~/.ssh/deploy_key ${{ vars.SSH_USER }}@${{ vars.SERVER_HOST }} \
            "cd /opt/one-button-game && docker-compose logs --tail=50"

      - name: Cleanup
        if: always()
        run: |
          rm -rf ~/.ssh/deploy_key
          rm -rf deploy_package
